title: Shajeer Ashraf
logo: \Shajeer Work\circular.png
descrption: Future Data Scientist | Pursuing Bachelor's in Computer Science | Seeking Opportunities to Apply Technical Skills
show_downloads: false
theme: jekyll-theme-minimal
